apiVersion: v1
kind: LimitRange
metadata:
  name: compute-resource-limits
  namespace: alpha
spec:
  limits:
  - default:
      cpu: 300m
      memory: 500Mi
    defaultRequest:
      cpu: 150m
      memory: 300Mi
    type: Container
